/**
 * The themes the gallery offers, and the one line of state that says which is on.
 *
 * Every colour lives in themes.css (generated by tools/gen-themes.mjs); picking a theme only
 * sets an attribute on <html> and lets the cascade do the rest. Midnight is the unqualified
 * `:root` block, so it is represented by the *absence* of the attribute — which is also what
 * the inline script in index.html assumes when it restores the choice before the first paint.
 */
export type Theme = { id: string; name: string; blurb: string; light: boolean }

export const THEMES: Theme[] = [
  { id: 'midnight', name: 'Midnight', blurb: 'Deep blue-black under an orange sun', light: false },
  { id: 'nebula', name: 'Nebula', blurb: 'Violet dust and a lilac accent', light: false },
  {
    id: 'terminal',
    name: 'Terminal',
    blurb: 'Phosphor green on near-neutral graphite',
    light: false,
  },
  { id: 'sunset', name: 'Sunset', blurb: 'Warm ash and a low gold sun', light: false },
  { id: 'glacier', name: 'Glacier', blurb: 'Cold slate under pale ice blue', light: false },
  { id: 'paper', name: 'Paper', blurb: 'Ink on warm white, for daylight', light: true },
]

const KEY = '1brain:theme'
const DEFAULT = 'midnight'
const listeners = new Set<(id: string) => void>()

let current = DEFAULT

export const themeId = () => current

/** Painted surfaces follow the cascade; anything that renders its own colours listens here. */
export function onTheme(fn: (id: string) => void): void {
  listeners.add(fn)
}

export function applyTheme(id: string): void {
  const next = THEMES.find((x) => x.id === id)?.id ?? DEFAULT
  current = next
  if (next === DEFAULT) delete document.documentElement.dataset.theme
  else document.documentElement.dataset.theme = next
  try {
    localStorage.setItem(KEY, next)
  } catch {}
  for (const fn of listeners) fn(next)
}

/** Reads back what the pre-paint script already applied, so boot never repaints. */
export function initTheme(): void {
  let saved: string | null = null
  try {
    saved = localStorage.getItem(KEY)
  } catch {}
  applyTheme(saved ?? DEFAULT)
}
